# Generated by Django 5.2.16 on 2026-07-10 20:09

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, help_text='Display name of the asset', max_length=255)),
                ('asset_tag', models.CharField(db_index=True, help_text='Unique asset identifier (e.g., AST-2024-00001)', max_length=64, unique=True, validators=[core.validators.AssetTagValidator()])),
                ('serial_number', models.CharField(blank=True, db_index=True, help_text='Manufacturer serial number', max_length=128, null=True, unique=True, validators=[core.validators.SerialNumberValidator()])),
                ('barcode', models.CharField(blank=True, db_index=True, help_text='Barcode or QR code value for scanning', max_length=128, null=True, unique=True)),
                ('category', models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('monitor', 'Monitor'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('printer', 'Printer'), ('scanner', 'Scanner'), ('server', 'Server'), ('network', 'Network Equipment'), ('phone', 'Phone'), ('tablet', 'Tablet'), ('software', 'Software License'), ('accessory', 'Accessory'), ('other', 'Other')], db_index=True, help_text='Asset category type', max_length=64)),
                ('subcategory', models.CharField(blank=True, help_text='Optional subcategory for finer classification', max_length=120)),
                ('manufacturer', models.CharField(blank=True, db_index=True, help_text='Manufacturer or brand name', max_length=255)),
                ('model', models.CharField(blank=True, db_index=True, help_text='Manufacturer model name or number', max_length=255)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('maintenance', 'Under Maintenance'), ('lost', 'Lost / Stolen'), ('disposed', 'Disposed'), ('retired', 'Retired')], db_index=True, default='available', help_text='Current lifecycle status of the asset', max_length=32)),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged'), ('needs_repair', 'Needs Repair'), ('retired', 'Retired')], db_index=True, default='good', help_text='Current physical or operational condition', max_length=32)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the asset')),
                ('purchase_date', models.DateField(blank=True, help_text='Date the asset was purchased', null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, help_text="Purchase cost in the organization's currency", max_digits=12, null=True, validators=[core.validators.validate_positive_cost])),
                ('warranty_expiry', models.DateField(blank=True, db_index=True, help_text='Date the manufacturer warranty expires', null=True)),
                ('warranty_provider', models.CharField(blank=True, help_text='Warranty provider name', max_length=255)),
                ('vendor_name', models.CharField(blank=True, help_text='Vendor/supplier name', max_length=255)),
                ('vendor_contact', models.CharField(blank=True, help_text='Vendor contact information', max_length=255)),
                ('location', models.CharField(blank=True, db_index=True, help_text='Physical location or room where the asset is kept', max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Photo of the asset', upload_to='assets/')),
                ('notes', models.TextField(blank=True, help_text='Internal notes or comments about the asset')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether the asset is currently active in the system')),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='JSON field for custom metadata')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['asset_tag'],
                'indexes': [models.Index(fields=['asset_tag', 'status'], name='assets_asse_asset_t_fc3384_idx'), models.Index(fields=['category', 'status'], name='assets_asse_categor_6e0f49_idx'), models.Index(fields=['manufacturer', 'model'], name='assets_asse_manufac_a025b8_idx'), models.Index(fields=['condition', 'status'], name='assets_asse_conditi_bab4c7_idx'), models.Index(fields=['purchase_date'], name='assets_asse_purchas_8495f5_idx'), models.Index(fields=['warranty_expiry'], name='assets_asse_warrant_21ad1b_idx'), models.Index(fields=['location'], name='assets_asse_locatio_6a133f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('purchase_cost__gte', 0), ('purchase_cost__isnull', True), _connector='OR'), name='check_purchase_cost_positive')],
            },
        ),
    ]
