# Generated by Django 5.2.16 on 2026-07-10 20:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('lost', 'Lost')], db_index=True, default='active', help_text='Current status of the assignment', max_length=32)),
                ('assigned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the asset was assigned')),
                ('returned_at', models.DateTimeField(blank=True, db_index=True, help_text='When the asset was returned', null=True)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, help_text='Expected return date/time', null=True)),
                ('expected_location', models.CharField(blank=True, help_text='Expected location of the asset during assignment', max_length=255)),
                ('department', models.CharField(blank=True, db_index=True, help_text='Department responsible for this assignment', max_length=120)),
                ('condition_on_assign', models.TextField(blank=True, help_text='Condition notes when the asset was assigned')),
                ('condition_on_return', models.TextField(blank=True, help_text='Condition notes when the asset was returned')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the assignment')),
                ('asset', models.ForeignKey(help_text='The asset being assigned', on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='assets.asset')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='The user who performed the assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(help_text='The user receiving the asset', on_delete=django.db.models.deletion.PROTECT, related_name='asset_assignments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['assigned_at', 'returned_at'], name='assignments_assigne_c365de_idx'), models.Index(fields=['status', 'due_at'], name='assignments_status_1261ed_idx'), models.Index(fields=['department', 'status'], name='assignments_departm_b623b7_idx'), models.Index(fields=['asset', 'status'], name='assignments_asset_i_33bfc5_idx'), models.Index(fields=['assigned_to', 'status'], name='assignments_assigne_8bc493_idx')],
            },
        ),
    ]
